[package]
name = "semsimian"
version = "0.1.15"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "semsimian"
crate-type = ["cdylib", "lib"]

[dependencies]
csv = "1.1.6"
dict = "0.1.5"
generator = "0.7.2"
ordered-float = "3.6.0"
pyo3 = { version = "*", features = ["extension-module"] }
indicatif = "*" # progress bar
rayon = "1.7.0"
