[package]
name = "semsimian"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "semsimian"
crate-type = ["cdylib", "lib"]

[dependencies]
csv = "1.1.6"
dict = "0.1.5"
generator = "0.7.2"
ordered-float = "3.6.0"
pyo3 = { version = "*", features = ["extension-module"] }
indicatif = "*" # progress bar
lazy_static = "1.4.0"
cargo-llvm-cov = "0.5.19"
rayon = "1.7.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }

[features]
ci = []

[profile.release]
codegen-units = 1
