name: QC for semsimian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test-linux:
    name: Test for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Build wheels for Linux
      uses: PyO3/maturin-action@v1
      with:
        rust-toolchain: stable
        target: ${{ matrix.target }}
        manylinux: auto
        args: --release --out dist -i 3.8 3.9 '3.10'
    - name: Install built wheel
      if: matrix.target == 'x86_64'
      run: |
        pip install semsimian --no-index --find-links dist --force-reinstall
        pip install pytest
        pytest
    - name: Run cargo test
      run: cargo test