name: QC for semsimian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write


jobs:

  test:
    name: Test for Linux & Windows
    strategy:
      matrix:
        python-version: [ '3.9', '3.11', '3.12' ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Build wheel
      uses: PyO3/maturin-action@v1
      with:
        rust-toolchain: stable
        target: 'x86_64'
        manylinux: auto
        args: --release --out dist -i ${{ matrix.python-version }}
    - name: Install built wheel and run all tests (Rust and Python)
      run: |
        # Set up

        pip install semsimian --no-index --find-links dist --force-reinstall
        pip install pytest pytest-cov
        cargo install cargo-llvm-cov
        cargo llvm-cov show-env --export-prefix
        cargo llvm-cov clean --workspace
        
        # The following commands run all rust tests, just like cargo test
        # The first version emits a report for further parsing
        # The second provides a plain-text report to the stdout
        # cargo llvm-cov --lcov --output-path coverage.lcov

        cargo llvm-cov --features ci

        # Convert the coverage report to more readable html
        
        # sudo apt-get install -y lcov
        # genhtml -o output coverage.lcov

        # run python tests
        pytest python/tests --cov-report xml --cov-report term-missing --capture=no

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3.1.1
    #   with:
    #     files: coverage.lcov,coverage.xml
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     name: semsimian-py-${{ matrix.python-version }}
    #     fail_ci_if_error: false
