name: QC for semsimian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write


jobs:

  test-linux:
    name: Test for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10' ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Build wheel
      uses: PyO3/maturin-action@v1
      with:
        rust-toolchain: stable
        target: 'x86_64'
        manylinux: auto
        args: --release --out dist -i ${{ matrix.python-version }}
    - name: Install built wheel and run all tests (Rust and Python)
      run: |
        # Set up
        pip install semsimian --no-index --find-links dist --force-reinstall
        pip install pytest pytest-cov
        cargo install cargo-llvm-cov
        cargo llvm-cov show-env --export-prefix
        cargo llvm-cov clean --workspace
        sudo apt-get install -y lcov
        
        # the following command runs all rust tests, just like cargo test
        cargo llvm-cov --lcov --output-path coverage.lcov

        # convert the coverage report to more readable html
        genhtml -o output coverage.lcov

        # run python tests
        pytest python/tests --cov-report xml

    - name: Store coverage reports on working branch
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      run: |
        git config user.email "username@users.noreply.github.com"
        git config user.name "GitHub Action"
        git add output/ coverage.lcov
        git commit -m "Update coverage report"
        git push origin/$BRANCH_NAME
        

